### ISSUE TITLE
Code Release of LLaVA - 7B

### ISSUE THREAD

**Issue by Sun-Haoyuan23** [luka-group/mDPO#1]
Hi,
I am highly impressed by the methods and results presented in your paper. Then, when will the residual portion of your code be subject to public dissemination?

**Comment by FeiWang96** [comment]
Hi Haoyuan,

Thank you for your interest in our work. We'll release the code for llava before EMNLP. It is largely based on the [LLAVA code](https://github.com/haotian-liu/LLaVA) with minor changes.
