### ISSUE TITLE
GPU Environment

### ISSUE THREAD

**Issue by huacong** [luka-group/mDPO#4]
Thanks for your excellent work! I have some questions about the GPU and running environment. Is the training environment for this work conducted on an A100? Is the work trained from scratch or fine-tuned with LoRA? How much GPU memory does the model occupy, and how much time will it take?

Best regards,

Cong Hua

**Comment by FeiWang96** [comment]
Hi, the training details can be found in our paper. We finetuned the model with LoRA. It takes a few hours on one A100 (80G) to finetune a 3B MLLM.
